#!/bin/bash

SCRIPT=$(readlink -f "$0")
CHROOT_PATH=$(dirname "$SCRIPT")
CHROOT_DIR="$CHROOT_PATH"/$(basename "$SCRIPT")-dir
USER=$(logname)

# mount proc, sys, dev
mount -t proc proc "$CHROOT_DIR"/proc
mount --rbind /sys "$CHROOT_DIR"/sys
mount --rbind /dev "$CHROOT_DIR"/dev
mount --make-rslave "$CHROOT_DIR"/sys
mount --make-rslave "$CHROOT_DIR"/dev

# auxiliary

function silent {
    $@ >/dev/null 2>&1
}

function in_chroot {
    chroot "$CHROOT_DIR" "$@"
}

function as_user_in_chroot {
    in_chroot su - -c "$@" "$USER"
}

function as_user_in_chroot_dir {
    as_user_in_chroot "cd $1 && ${@:2}"
}

function user_exists {
    silent in_chroot id -u "$USER"
}

function user_add {
    silent in_chroot useradd -m -G wheel "$USER"
}

function init_env {
    in_chroot emerge-webrsync
    in_chroot layman -S
    in_chroot eix-sync

    as_user_in_chroot "cabal update"

    as_user_in_chroot "git clone https://github.com/ekmett/linear"
    as_user_in_chroot_dir "linear" "cabal install"

    as_user_in_chroot "git clone https://github.com/diagrams/diagrams-lib"
    as_user_in_chroot_dir "diagrams-lib" "cabal install"

    as_user_in_chroot "git clone https://github.com/diagrams/diagrams-cairo"
    as_user_in_chroot_dir "diagrams-cairo" "cabal install"

    as_user_in_chroot "git clone https://github.com/diagrams/diagrams-gtk"
    as_user_in_chroot_dir "diagrams-gtk" "cabal install"

    as_user_in_chroot "git clone https://github.com/d3sformal/bacon"
    as_user_in_chroot_dir "bacon" "git checkout experimental"
    as_user_in_chroot_dir "bacon/bacon" "cabal install --dependencies-only --force-reinstalls"
}

# enable networking, X
cp -L /etc/resolv.conf "$CHROOT_DIR"/etc/resolv.conf
cp ~/.Xauthority "$CHROOT_DIR"/~"$USER" 2>/dev/null

# init user
if ! user_exists; then
    user_add
    init_env
fi

# chroot
chroot "$CHROOT_DIR" su - "$USER"

# umount proc, sys, dev
mount -l | cut -d" " -f3 | grep "^$CHROOT_DIR" | sort -ur | xargs umount
